version: "3.9"
services:
  postgis:
    image: postgres:15.1-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgis_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: db
      POSTGRES_DB: db
      POSTGRES_PASSWORD: secret
    restart: unless-stopped

  #  pgadmin:
  #    image: dpage/pgadmin4
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@beacon-v3.com}
  #      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #    volumes:
  #      - pgadmin:/root/.pgadmin
  #    ports:
  #      - "${PGADMIN_PORT:-5050}:80"
  #    restart: unless-stopped

volumes:
  postgis_data: {}
  pgadmin: {}