version: "3.3"
services:
  database:
    image: postgres:15.1-alpine
    ports:
      - '9000:5432'
    volumes:
      - postgis_data:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    env_file: .env

volumes:
  postgis_data: {}
  pgadmin: {}
  gem_cache: {}