version: "3.3"
services:
  app:
    image: docker.io/trekmedics/case-reports-ms:${TAG:-latest}
    ports:
      - "3001:3000"
    env_file: .env
    command:
      - start

volumes:
  postgis_data: {}
  pgadmin: {}
  gem_cache: {}