name: Delete old artifacts manually
on: [workflow_dispatch]

jobs:
  delete:
    name: Delete Old Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            async function deleteArtifacts() {
              const res = await github.rest.actions.listArtifactsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              for (const artifact of res.data.artifacts) {
                try {
                  await github.rest.actions.deleteArtifact({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    artifact_id: artifact.id,
                  });
                  console.log(`Artifact ${artifact.id} deleted`);
                } catch (error) {
                  console.error(`Error deleting artifact ${artifact.id}: ${error}`);
                }
              }
            }
            deleteArtifacts();
